title: "Jesper Olsen's Resume"
description: "Mechatronics Engineer | 3D Printing Enthusiast | Environmental Researcher"
baseurl: "" # leave this empty if you're using the default username.github.io domain
url: "https://your-username.github.io" # replace with your GitHub Pages URL
theme: minima # or any Jekyll theme you'd like to use
author:
  name: "Jesper Olsen"
  email: "jespero@devkon.me"
  bio: "Mechatronics Engineer with a passion for 3D printing and ecological projects."
  location: "Norway"

# Social links (optional)
social_links:
  - github: your-github-username
  - linkedin: your-linkedin-profile

# Jekyll settings
markdown: kramdown
highlighter: rouge

# Navigation (optional)
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about/"
  - name: "Projects"
    link: "/projects/"
  - name: "Contact"
    link: "/contact/"
